spring:
  application:
    name: MAGE
  datasource:
      url: jdbc:mysql://localhost:3306/MAGE
      username: root
      password: Tg-Mage25!
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true